---
- hosts: all 
  become: yes
  
  tasks:
  - name: Update APT
    ansible.builtin.apt:
       update_cache: true
  - name: Install Python
    ansible.builtin.package:
       name: python-apt
       state: present
  - name: Install Apache
    ansible.builtin.package:
       name: apache2
       state: present
  - name: Symbolic Link
    ansible.builtin.file:
       src: /etc/apache2/mods-available/headers.load
       dest: /etc/apache2/mods-enabled/headers.load
       state: link
  - name: restart apache2
    ansible.builtin.service:
       name: apache2
       state: restarted
vars:
   mysql_import_data: "yes"
